fix: remove wildcard (`*`) dependency constraint for crate publishing (#105)
Also sanitizes the READMEs a bit.

The last attempt to publish a crate using release PR #98
[failed](https://github.com/CQCL/hugr-llvm/actions/runs/10886782954/job/30207610938)
with:
```
error: failed to publish to registry at https://crates.io/
    
    Caused by:
      the remote server responded with an error (status 400 Bad Request): wildcard (`*`) dependency constraints are not allowed on crates.io. Crate with this problem: `serde` See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
```