test: Print `hugr-cli`'s errors on python tests (#1310)
Prints the error returned by `hugr-cli` when something fails, so we get
better feedback.

Before:
```
subprocess.CalledProcessError: Command '['/Users/agustinborgna/src/hugr/target/debug/hugr', '-']' returned non-zero exit status 1.
```

After:
```
RuntimeError: Error validating HUGR: Parent node Node(0) has extensions [] that are too restrictive for child node Node(5), they must include child extensions [IdentList("quantum.tket2")]
```