fix: Move `declarative.yaml` example to the `hugr-core` crate (#1131)
This is a file used for the `hugr-core` docs, so it should be included
in that crate.

When trying to `cargo publish`, I got an error due to it not getting
packaged.
```
error: couldn't read src/extension/../../../hugr/examples/extension/declarative.yaml: No such file or directory (os error 2)
  --> src/extension/declarative.rs:12:10
   |
12 | #![doc = include_str!("../../../hugr/examples/extension/declarative.yaml")]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
```